#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l pmem=16gb
#PBS -l walltime=36:00:00
#PBS -M coalhende@gmail.com
#PBS -N snakemake_run
#PBS -m abe

# -------------------------------------------------- #
#Run Snakemake!
# -------------------------------------------------- #

#move to correct directory
cd /storage/home/c/cah422/scratch/anophGenome-august2019/ 

#run snakemake
conda activate bioinfo
snakemake --unlock
snakemake --ri -j 25 --cluster-config cluster.yaml --cluster "qsub -A {cluster.QUEUE} -l walltime={cluster.WALLTIME} -l nodes={cluster.NODES}:ppn={cluster.PPN} -l pmem={cluster.PMEM} -M {cluster.EMAIL} -m abe"

exit;
